# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html[package]

[package]
name = "rust-api"
version = "0.1.0"

[dependencies]
actix-web = "4"
diesel = { version = "^2.0.0", features = ["postgres"] }
dotenvy = "0.15"
serde_json = "1.0.0"
