version: '3.9'

services:
  postgres:
    image: postgres:15.1
    expose:
      - "5432"
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    volumes:
      - pkmdb:/var/lib/postgresql/data

  app:
    build: .
    expose:
      - "8080"
    ports:
      - 8080:8080
    command: 
      - sh -c "diesel setup"
      - sh -c "cargo run"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
  
volumes:
  pkmdb: {}