version: '3.9'

x-shared-environment: &shared-environment
  - POSTGRES_DB="postgres"
  - POSTGRES_USER="postgres"
  - POSTGRES_PASSWORD="postgres"

services:
  postgres:
    image: postgres:15.1
    restart: always
    environment: *shared-environment
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - pkmdb:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "cargo run"
    environment: 
      - <<*shared-environment
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    volumes:
      - .:/app
    ports:
      - 8080:8080
    expose:
      - "8080"
    depends_on:
      - postgres
  
volumes:
  pkmdb: {}