version: '3.9'

services:
  db:
    image: postgres:15.1
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - apiDB:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    command: bash -c "cargo run"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    expose:
      - "8080"
    depends_on:
      - db
  
volumes:
  apiDB: {}